name: Valtteri Wikström
markdown: redcarpet
pygments: true

gems: [jekyll-scholar]

scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

  source: ./
  bibliography: mypublications
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"