name: Valtteri Wikström
markdown: redcarpet
#pygments: true
highlighter: pygments

destination: ../_site

title:            From Töölö with Love
description:      Stuff and things I've done.
logo:             site-logo.png
disqus_shortname: vatte
search:           false
# Your site's domain goes here. When working locally use localhost server leave blank
# PS. If you set this wrong stylesheets and scripts won't load and most links will break.
# PPS. If you leave it blank for local testing home links won't work, they'll be fine for live domains though.
url:              http://vatte.github.io # http://localhost:4000 # #http://192.168.0.17:4000 # 

owner:
  name:     Valtteri Wikström
  avatar:   avatar.png
  email:    vatte.wikstrom@gmail.com
  github:   vatte


links:
  - title: Home
    url: /
  - title: Projects
    url: /projects/
  - title: Research
    url: /research.html
  - title: Teaching
    url: /teaching/
  - title: About
    url: /about/

exclude: [wip_pages, wip_posts]

scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

  source: ./
  bibliography: mypublications
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
